### ISSUE TITLE
🐛 Bug Report: app fails to start if Native Instruments dir exists with no Traktor config

### ISSUE THREAD

**Issue by apreeel** [whatsnowplaying/whats-now-playing#692] opened 2023-03-02 01:38 UTC
### 📜 Description

When open app at first time it asks to access Documents folder and also firewall triggers that it trying to access some host, but then it exit before even some gui appears. There is now app icon in dock or anything.
When trying to run executable from .app contents it fails with _[1466] Failed to execute script 'nppyi' due to unhandled exception!_ message, see full log. 
Both result for Intel and ARM version.
Mac OS 13.2.1, M1 Pro.

```
tabacyclone@mbp14apreeel ~ % /Applications/NowPlaying.app/Contents/MacOS/NowPlaying ; exit;
Traceback (most recent call last):
  File "nppyi.py", line 14, in <module>
  File "nowplaying/__main__.py", line 77, in main
  File "nowplaying/__main__.py", line 63, in actualmain
  File "nowplaying/config.py", line 83, in __init__
  File "nowplaying/config.py", line 207, in defaults
  File "nowplaying/config.py", line 231, in _defaults_plugins
  File "nowplaying/inputs/traktor.py", line 177, in __init__
  File "nowplaying/inputs/icecast.py", line 154, in __init__
  File "nowplaying/inputs/__init__.py", line 18, in __init__
  File "nowplaying/inputs/traktor.py", line 204, in defaults
IndexError: list index out of range
[1466] Failed to execute script 'nppyi' due to unhandled exception!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...       2 completed.

[Process completed]
```

### 👟 Reproduction steps

Run the app.
Or run the NowPlaying executable from NowPlaying.app/Contents/MacOS/ for terminal log output.

### 👍 Expected behavior

I was expected to see some GUI.

### 👎 Actual Behavior

But it even won't start.

### 💻 Operating system

MacOS

### 💻 Chipset/CPU

Apple M1

### 💻 Input source

Serato

**Comment by aw-was-here** [comment] 2023-03-02 02:00
Hmm. Weird. I actually run all the time on M1, so I wonder if it is something else. Thanks for the bug report! I'll take a look.

**Comment by aw-was-here** [comment] 2023-03-02 02:01
By chance, do you have a Traktor directory on your system?

**Comment by apreeel** [comment] 2023-03-02 11:14
d No, Traktor was never installed, so I suppose there is no Traktor directory. 
I goggled where it should be and there is no any Traktor directories.

**Comment by apreeel** [comment] 2023-03-02 15:16
After renaming NI directory app runs with next message:
`Configured source None is not supported. Reconfiguring.`
Then i got this:
![image](https://user-images.githubusercontent.com/78701382/222467674-8d758038-ecbb-4dcc-914f-9e4d421ab07d.png)
Then it closes.
Also it generates some log files:

`2023-03-02T16:09:52+0100 4255 MainProcess/MainThread __main__:run_bootstrap:34 INFO starting up v4.0.0
2023-03-02T16:09:52+0100 4255 MainProcess/MainThread upgrade:upgrade:456 DEBUG Called upgrade
2023-03-02T16:09:52+0100 4255 MainProcess/MainThread connectionpool:_new_conn:1003 DEBUG Starting new HTTPS connection (1): api.github.com:443
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread connectionpool:_make_request:456 DEBUG https://api.github.com:443 "GET /repos/whatsnowplaying/whats-now-playing/releases HTTP/1.1" 200 9831
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread trackrequests:setupdb:98 DEBUG Setting up the database /Users/tabacyclone/Library/Caches/whatsnowplaying/NowPlaying/requests/request.db
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread upgrade:backup_config:234 INFO Making a backup of config prior to upgrade: /Users/tabacyclone/Documents/NowPlaying/configbackup
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread upgrade:upgrade:292 INFO Upgrading config from 4.0.0 to 4.0.0
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread upgrade:upgrade:303 DEBUG processing acoustidmb/emailaddress - musicbrainz/emailaddress
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread upgrade:upgrade:324 DEBUG acoustidmb/emailaddress does not exist
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread upgrade:upgrade:303 DEBUG processing acoustidmb/enabled - musicbrainz/enabled
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread upgrade:upgrade:324 DEBUG acoustidmb/enabled does not exist
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread upgrade:upgrade:303 DEBUG processing twitchbot/enabled - twitchbot/chat
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread upgrade:upgrade:324 DEBUG twitchbot/enabled does not exist
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread upgrade:upgrade:303 DEBUG processing twitchbot/token - twitchbot/chattoken
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread upgrade:upgrade:324 DEBUG twitchbot/token does not exist
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread __main__:run_bootstrap:37 DEBUG ending upgrade
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread db:setupsql:265 INFO Clearing cache file /Users/tabacyclone/Library/Caches/whatsnowplaying/NowPlaying/metadb/npsql.db
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread db:setupsql:276 DEBUG Cache db file created
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread config:__init__:57 INFO Logpath: /Users/tabacyclone/Documents/NowPlaying/logs
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread config:__init__:58 INFO Templates: /Users/tabacyclone/Documents/NowPlaying/templates
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread config:__init__:59 INFO Bundle: /Applications/NowPlaying.app/Contents/MacOS
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread config:__init__:60 DEBUG SSL_CERT_FILE=/Applications/NowPlaying.app/Contents/MacOS/certifi/cacert.pem
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread config:__init__:61 DEBUG SSL CA FILE=/Applications/NowPlaying.app/Contents/MacOS/certifi/cacert.pem
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread config:__init__:71 INFO configuration: /Users/tabacyclone/Library/Preferences/com.whatsnowplaying.NowPlaying.plist
2023-03-02T16:09:53+0100 4255 MainProcess/MainThread config:defaults:139 DEBUG set defaults
`

After renaming NI directory back to it's original name behavior returns to what i described earlier. It fails to run and provide similar log output.

**Comment by aw-was-here** [comment] 2023-03-02 15:18
Does it close or does it keep running in the system tray? It should stay up in the system tray.

**Comment by apreeel** [comment] 2023-03-02 15:24
As I can see with Activity Monitor the process quits.
There is tray icon, but I can't access setting from here.

**Comment by aw-was-here** [comment] 2023-03-02 15:32
Chances are, if you relaunch without the NI directory again it will boot as normal now that it has a config.  But that's obviously not ideal.  Let me play around with a new install and see if I can duplicate.  I have a hunch I know what the problem is but will need some time to verify.

Thanks for all the bug info!

**Comment by aw-was-here** [comment] 2023-03-02 15:36
Actually, after Basic Configuration, you _should_ be getting the Settings window popped up, but it might be hidden by other windows.  Menu will be disabled during this initial install.

**Comment by aw-was-here** [comment] 2023-03-02 15:55
OK, i've tracked down the issue. Very subtle bug!

The usual flow should be:

1. Run binary.
2. Software attempts to figure out what is running.
3. Flashes up the 'Basic Configuration' window you got above.
4. Pops up the Settings window so you can make adjustments

There's an unrelated crash in the middle of 3 and 4 due to a recent change where the UI code isn't fully loaded yet.  It looks like another simple fix.  Gotta love these x.0.0 releases. Sigh.

**Comment by aw-was-here** [comment] 2023-03-02 17:01
After a lot more digging, it is very clear that I broke fresh installs a few revs back and no one caught it. Sigh.

**Comment by aw-was-here** [comment] 2023-03-02 18:49
Just published 4.0.1 which should fixed all of the above issues.  🤞

**Comment by apreeel** [comment] 2023-03-02 19:00
It runs successfully!
Thank you so much. I'm gonna go figure out how it works for now. 🫶🏻

**Comment by aw-was-here** [comment] 2023-03-02 19:08
Awesome! Thanks for sticking with it while we debugged. 😄   I'm going to close this one out.  If something new pops up, feel free to file some issues.

**Closed by aw-was-here** 2023-03-02 19:08 UTC
Labels: bug, 4.x.x
